# Generated by Django 4.2.1 on 2023-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='resume',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
