# Generated by Django 4.2.1 on 2023-06-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_form_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='resume',
        ),
    ]
